# Generated by Django 5.2.6 on 2025-09-22 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'verbose_name': 'Медиафайл', 'verbose_name_plural': 'Медиафайлы'},
        ),
        migrations.RemoveField(
            model_name='postmedia',
            name='file_type',
        ),
        migrations.AddField(
            model_name='postmedia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(upload_to='post_media/'),
        ),
    ]
